version: '3.9'

services:
  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'api-base-database'
    volumes:
      - pg-data:/postgresql/data
    environment:
      POSTGRES_USER: NewAppUser
      POSTGRES_PASSWORD: NewPassword
      POSTGRES_DB: apibase
volumes:
  pg-data: