service: graphql-base-api
frameworkVersion: '>=3'

plugins:
  - serverless-plugin-typescript
  - serverless-ssm-fetch
  - serverless-offline

package:
  individually: true
  patterns:
    - '**/*.gql'
    - '!dist/**'

custom:
  serverlessSsmFetch:
    DATABASE_URL: /dev/database/url~true
    APOLLO_KEY: /dev/apollo/key
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 2048
  timeout: 10
  region: us-east-1
  logRetentionInDays: 14
  vpc:
    securityGroupIds:
      - sg-00000000000000000
      - sg-11111111111111111
    subnetIds:
      - subnet-0123456789abcdef0
      - subnet-213456789abcdef0

functions:
  main:
    #handler: src/index.graphqlHandler
    handler: src/lambda.handler
    ssmToEnvironment:
      - DATABASE_URL
      - APOLLO_KEY
    environment:
      NODE_ENV: production
      # https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    package:
      # see https://github.com/serverless/serverless-plugin-typescript/issues/170#issuecomment-1132731263
      patterns:
        - '!node_modules/.prisma/client/libquery_engine-*'
        - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
        - '!node_modules/prisma/libquery_engine-*'
        - '!node_modules/@prisma/engines/**'
  graph:
    handler: src/index.graphqlHandler
    #handler: src/lambda.handler
    ssmToEnvironment:
      - DATABASE_URL
      - APOLLO_KEY
    environment:
      NODE_ENV: production
      # https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    events:
      - http:
          method: ANY
          path: /gql
    package:
      # see https://github.com/serverless/serverless-plugin-typescript/issues/170#issuecomment-1132731263
      patterns:
        - '!node_modules/.prisma/client/libquery_engine-*'
        - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
        - '!node_modules/prisma/libquery_engine-*'
        - '!node_modules/@prisma/engines/**'